### PR TITLE
Bug: Multiple token requests

### LINKED ISSUE #54: Bug: Multiple tokens might be allocated from Warden
Sometimes Tokend makes multiple requests to Warden to get a token and ends up keeping two tokens alive at the same time. I suspect it's a race condition that happens during our initial token retrieval in the `TokenProvider`.

### PR DESCRIPTION
**Pull request by dgreene-r7**
This PR fixes #54. A race condition previously existed where two `defaultToken`s would be retrieved at the same time. This requires all token provisioning to require the `defaultToken` to be initialized before `initialize()` is called on their `LeaseManager`.

In addition, it refactors some of the `LeaseManager` to be a bit more stateful.

### CODE REVIEW

File: lib/lease-manager.js [hunk 1]
```diff
@@ -33,45 +56,48 @@ class LeaseManager extends EventEmitter {
...
-        this.lease_duration = result.lease_duration;
-        this.data = result.data;
-        this.emit('renewed');
+        this.emit('renewed', result);
         this._renew();
       }).catch((err) => {
-        this.error = err;
-        this.status = STATUS.PENDING;
-        this.lease_duration = 0;
+        this.emit('error', err);
```
Comment (fmitchell-r7) [inline lib/lease-manager.js]: Previously, `this.data` wasn't being cleared if we failed to renew, because there's some period of time where the secret is still valid. I think we want to keep the behavior of only clearing `this.data` if the `initialize()` call fails.

File: lib/lease-manager.js [hunk 2]
```diff
@@ -33,45 +59,48 @@ class LeaseManager extends EventEmitter {
...
     return this.provider.initialize().then((result) => {
-      this.status = STATUS.READY;
       this.data = result.data;
       this.lease_duration = result.lease_duration;
-      this.emit('ready');
-      this.error = null;
+
       this._renew();
+      if (this.status !== STATUS.READY) {
+        this.emit('ready');
```
Comment (fmitchell-r7) [inline lib/lease-manager.js]: I think the state transition to `READY` needs to happen before the call to `this._renew()`. Otherwise, if the renew timeout fires immediately (the secret has no lease duration) and errors, the data will be cleared.

Comment (dgreene-r7) [inline lib/lease-manager.js]: You're right. Changes in e54de67.

**Comment by fmitchell-r7** [comment]
👍  Thanks for fixing this! I'd get a review from @jmanero-r7 and then 🚢  it.
